### PR TITLE
chore(object-storage): numerous improvements in headers handling

### PR DESCRIPTION
**Pull request by dtantsur**
Follow-up to #109

### CODE REVIEW

**Comment by ilourt** [comment]
@dtantsur soory for the delay I was not available. I see that you have implemented the modifications. Let me know if I can help you.

**Comment by dtantsur** [comment]
Hi, no worries! Now I only need to understand why the CI fails..

**Comment by dtantsur** [comment]
recheck

**Comment by dtantsur** [comment]
recheck

**Pull request merged**
