### PR TITLE
Add .zuul.yaml file and playbooks directory

### PR DESCRIPTION
**Pull request by mrhillsman**
The .zuul.yaml is YAML-formatted configuration file for repositories managed by Zuul

The playbooks directory is created to encourage using Ansible best practices:
http://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>

### CODE REVIEW

**Comment by mrhillsman** [comment]
Related to #15

**Comment by dtantsur** [comment]
Thanks!

> The playbooks directory is created to encourage using Ansible best practices

I don't see this directory in the PR. Is it intended? Maybe you need to add .gitkeep to it?

**Comment by mrhillsman** [comment]
Ah yeah, the .gitkeep cause it is indeed empty, apologies.

**Comment by mrhillsman** [comment]
@dtantsur once this is merged we can create a PR to ensure the noop succeeds

**Comment by dtantsur** [comment]
Thank you!

**Pull request merged**
