### PR TITLE
Experimental - Run Github Action for CI

### PR DESCRIPTION
**Pull request by EmilienM**
To demonstrate how fast & easy it is.
The tests will fail, as it's missing some environment variables, but you
get the idea.

### CODE REVIEW

**Comment by EmilienM** [comment]
@dtantsur if you can enable Github Actions for this repo, so I can finish my demo :-)
Thanks

**Comment by dtantsur** [comment]
@EmilienM do you have an idea how to do that? they seem enabled in settings. maybe only I can add the initial workflow?

**Comment by EmilienM** [comment]
@dtantsur https://github.com/dtantsur/rust-openstack/settings/actions - I think you need to click on "Allow all actions".

**Comment by dtantsur** [comment]
@EmilienM it's already set to that value.

**Comment by EmilienM** [comment]
@dtantsur do you have to click of Approve the run (a button bellow, near merge) ?

**Comment by EmilienM** [comment]
BTW tests ran fine here: https://github.com/EmilienM/rust-openstack/runs/4767633944?check_suite_focus=true
22 min to deploy Devstack and install cargo (and then fail on the tests), pretty fast uh?
Maybe you could help me to finish the part that runs tests, so we can see how long it takes end to end.

**Comment by dtantsur** [comment]
@EmilienM nope. I've created a stub https://github.com/dtantsur/rust-openstack/blob/master/.github/workflows/functional.yml, could you rebase your patch and update this file? Maybe with my blessing it will work?

**Comment by EmilienM** [comment]
@dtantsur now I need approval :)

**Comment by dtantsur** [comment]
Trying for real on https://github.com/dtantsur/rust-osauth/pull/61

**Comment by EmilienM** [comment]
I'm closing it for now, I have no time to work on it but I'll be super happy if this was useful to this project. I really believe that it helped Gophercloud to get a more stable & reliable & faster CI without too much work.

**Pull request closed without merging**
